-- Create the meals table
/*CREATE TABLE meals (
                       id INTEGER PRIMARY KEY AUTOINCREMENT,
                       food_item TEXT NOT NULL,
                       serving_size TEXT,
                       calories INTEGER,
                       health_score INTEGER,
                       price INTEGER
);

-- Insert data into the meals table
INSERT INTO meals (food_item, serving_size, calories, health_score, price) VALUES
                                                                               ('Pounded Yam', '1 wrap(200g)', 470, 5, 200),
                                                                               ('Amala', '1 wrap (190g)', 352, 5, 200),
                                                                               ('Eba', '1 wrap (200g)', 400, 5, 200),
                                                                               ('Fufu', '1 wrap (200g)', 370, 5, 200),
                                                                               ('Semo', '1 wrap(200g)', 350, 5, 200),
                                                                               ('Boiled Yam', '1 portion', 177, 7, 300),
                                                                               ('Boli (Roasted Plantain)', '1 serving(100g)', 204, 7, 300),
                                                                               ('White Rice', '1 portion(186g)', 205, 6, 300),
                                                                               ('Fried Rice', '1 portion(186g)', 250, 5, 300),
                                                                               ('Jollof Rice', '1 portion (150g)', 310, 5, 300),
                                                                               ('Ofada Rice (with sauce)', '1 portion', 250, 6, 300),
                                                                               ('Spaghetti (White)', '1 portion (140g)', 220, 5, 300),
                                                                               ('Spaghetti (Stir Fry)', '1 portion (150g)', 400, 6, 300),
                                                                               ('Moi Moi', '1 wrap (250g)', 315, 7, 400),
                                                                               ('Akara', '1 ball', 270, 5, 100),
                                                                               ('Beans (Plain)', '1 portion (180g)', 240, 9, 400),
                                                                               ('Ewa Agoyin', '1 portion', 300, 9, 400),
                                                                               ('Yam Porridge', '1 portion (250g)', 280, 8, 400),
                                                                               ('Efo Riro', '1 serving (240g)', 178, 9, 0),
                                                                               ('Edikang Ikong Soup', '1 serving (240g)', 280, 9, 0),
                                                                               ('Egusi Soup', '1 serving (252g)', 306, 5, 0),
                                                                               ('Ogbono Soup', '1 serving(238g)', 174, 6, 0),
                                                                               ('Ewedu Soup', '1 serving (240g)', 97, 7, 0),
                                                                               ('Gbegiri Soup', '1 serving (240g)', 190, 5, 0),
                                                                               ('Okra Soup', '1 serving (240g)', 160, 6, 0),
                                                                               ('Afang Soup', '1 serving (240g)', 361, 5, 0),
                                                                               ('Nsala Soup', '1 serving (240g)', 180, 5, 0),
                                                                               ('Banga Soup', '1 serving(240g)', 340, 7, 0),
                                                                               ('Ugwu Soup', '1 serving (240g)', 280, 8, 0),
                                                                               ('Black Soup', '1 serving(240g)', 190, 8, 0),
                                                                               ('Stew', '1 serving', 288, 6, 0),
                                                                               ('Coleslaw', '1 cup (150g)', 180, 7, 200),
                                                                               ('Groundnut (Peanuts)', '1 wrap(100g)', 567, 7, 100),
                                                                               ('Suya', '100g', 315, 5, 500),
                                                                               ('Fried Meat (Beef)', '50g', 250, 6, 200),
                                                                               ('Peppered Chicken', '1 piece (100g)', 280, 7, 1200),
                                                                               ('Fried Turkey', '1 piece (100g)', 320, 7, 1200),
                                                                               ('Ponmo (Cow Skin)', '1 piece (50g)', 110, 8, 300),
                                                                               ('Eja Kika', '1 piece (150g)', 250, 5, 750),
                                                                               ('Toast Bread Sandwich', '1 slice + filling', 350, 5, 400),
                                                                               ('Bread (Agege)', '1 loaf (200g)', 500, 4, 400),
                                                                               ('Coconut Rice', '1 serving', 330, 6, 400),
                                                                               ('Fried Plantain', '1 portion(4 slices)', 365, 5, 200),
                                                                               ('Yamarita', '1 portion', 400, 5, 400),
                                                                               ('Pepper Soup + Catfish', '1 serving', 380, 8, 3000),
                                                                               ('Fried Yam', '1 slice', 400, 4, 100),
                                                                               ('Goat meat pepper soup', '1 serving', 270, 7, 3000),
                                                                               ('Fried egg', '1 egg', 210, 6, 350),
                                                                               ('Catfish', '1 portion', 230, 8, 1800);*/