spring.application.name=nurtibudget
server.port=8080

# SQLite Database Configuration
#spring.datasource.url=jdbc:sqlite:meals.db
#spring.datasource.driver-class-name=org.sqlite.JDBC
#spring.jpa.database-platform=org.hibernate.dialect.SQLiteDialect
#spring.datasource.username=
#spring.datasource.password=


# Disable DataSource auto-configuration
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration